# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources and build and deploy Function App
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "PythonDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #    - 'src/FunctionApp/*'
  #   exclude:
  #     - '**/*.md'

parameters:
  # - name: runCodeScan
  #   displayName: Run Security Scan
  #   default: true
  #   type: boolean
  - name: image
    displayName: Pool Image
    type: string
    default: ubuntu-latest
    values:
    - windows-latest
    - ubuntu-latest
    - macOS-latest
# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-and-function-pipe.yml
  parameters:
    variableGroupName: 'PythonDemo'
    environments: ['DEV','PROD']
    runCodeScan: true
    #runCodeScan: {{ parameters.runCodeScan }}
