# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Application Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runCodeScan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(variables['runCodeScan'], 'true') }} :
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/secure-devops-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/build-python-function-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - ${{ if eq(upper(environmentName), 'DEV') }}:
    - stage: DeployApp${{ environmentName }}
      displayName: Deploy ${{ environmentName }} Application
      jobs:
      - template: templates/deploy-function-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}

  - ${{ if eq(upper(environmentName), 'PROD') }}:  
    - stage: DeployApp${{ environmentName }}
      dependsOn: DeployAppDev
      condition: succeeded('DeployAppDev')
      displayName: Deploy ${{ environmentName }} Application
      jobs:
      - template: templates/deploy-function-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}
