# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to build and deploy Azure Resources and Application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runCodeScan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(variables['runCodeScan'], 'true') }} :
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/secure-devops-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- stage: BuildApplication
  displayName: Build Application
  jobs:
  - template: templates/build-python-function-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - ${{ if eq(upper(environmentName), 'DEV') }}:
    - stage: CreateInfrastructure${{ environmentName }}
      displayName: ${{ environmentName }} Infrastructure
      dependsOn: BuildApplication
      condition: succeeded('BuildApplication')
      jobs:
      - template: templates/create-infra-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}

    - stage: Deploy${{ environmentName }}App
      displayName: Deploy ${{ environmentName }} App
      dependsOn: CreateInfrastructure${{ environmentName }}
      condition: succeeded('CreateInfrastructure${{ environmentName }}')
      jobs:
      - template: templates/deploy-function-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}

  - ${{ if eq(upper(environmentName), 'PROD') }}:  
    - stage: CreateInfrastructure${{ environmentName }}
      displayName: ${{ environmentName }} Infrastructure
      dependsOn: CreateInfrastructureDev
      condition: succeeded('CreateInfrastructureDev')
      jobs:
      - template: templates/create-infra-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}

    - stage: Deploy${{ environmentName }}App
      displayName: Deploy ${{ environmentName }} App
      dependsOn: CreateInfrastructure${{ environmentName }}
      condition: succeeded('CreateInfrastructure${{ environmentName }}')
      jobs:
      - template: templates/deploy-function-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}
