# ------------------------------------------------------------------------------------------------------------------------
# Pipeline Template to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: environments
  type: object
  default: ['DEV']
- name: variableGroupName
  default: 'myVariableGroupName'
- name: runCodeScan
  type: boolean
  default: false

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if eq(variables['runCodeScan'], 'true') }} :
  - stage: ScanApplication
    displayName: Scan Application
    jobs:
    - template: templates/secure-devops-template.yml
      parameters:
        variableGroupName: ${{ parameters.variableGroupName }}
        environmentName: 'DEV'

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentName in parameters.environments }} :
  - ${{ if eq(upper(environmentName), 'DEV') }}:
    - stage: CreateInfrastructure${{ environmentName }}
      displayName: ${{ environmentName }} Infrastructure
      variables:
        group: ${{ parameters.variableGroupName }}
      jobs:
      - template: templates/create-infra-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}
          deployToSubscription: ${{ subscriptionNameDev }}
          deployToResourceGroup: ${{ resourceGroupDev }}

  - ${{ if ne(upper(environmentName), 'DEV') }}:  
    - stage: CreateInfrastructure${{ environmentName }}
      displayName: ${{ environmentName }} Infrastructure
      dependsOn: CreateInfrastructureDev
      condition: succeeded('CreateInfrastructureDev')
      variables:
        group: ${{ parameters.variableGroupName }}
      jobs:
      - template: templates/create-infra-template.yml
        parameters:
          variableGroupName: ${{ parameters.variableGroupName }}
          environmentName: ${{ environmentName }}
          deployToSubscription: ${{ subscriptionNameProd }}
          deployToResourceGroup: ${{ resourceGroupProd }}
